---
name: diabetes
description: Du An 2
publish_to: none
version: 0.1.0
environment:
  sdk: '>=3.2.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.1
  dio: ^4.0.5
  dio_log: ^2.0.4
  equatable: ^2.0.3
  firebase_dynamic_links: ^5.4.17
  flutter_html: 3.0.0-beta.2
  path_provider: ^2.0.5
  share: ^2.0.4
  hive_flutter: ^1.1.0
  flutter_chat_ui: ^1.6.9
  file_picker: ^5.3.2
  open_filex: ^4.3.2
  flutter_chat_types: ^3.6.1
  http: ^0.13.6
  flutter_bloc: ^7.0.1
  firebase_auth: ^4.15.2
  firebase_core: ^2.26.0
  firebase_storage: ^11.6.7
  flutter_secure_storage: ^9.0.0
  sliding_up_panel: ^2.0.0+1
  custom_timer: ^0.0.6
  smooth_page_indicator: ^1.1.0
  percent_indicator: ^4.0.2
  video_player: ^2.1.12
  chewie: ^1.7.5
  image_picker: ^1.0.7
  awesome_notifications: ^0.8.3
  awesome_notifications_core: any
  awesome_notifications_fcm: any
  flutter_timezone: ^1.0.8
  permission_handler: ^11.3.0
  url_launcher: ^6.0.9
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.5.1
  fluentui_system_icons: ^1.1.231
  figma_squircle: ^0.5.3
  intl: ^0.19.0
  flutter_fadein: ^2.0.0
  shimmer: ^3.0.0
  cloud_firestore: ^4.15.8
  uuid: ^4.3.3
  jiffy: ^6.2.2
  get_it: ^7.6.7
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
  - assets/images/onboarding/
  - assets/images/auth/
  - assets/images/exercises/
  - assets/images/home/
  - assets/icons/home/
  - assets/icons/social_networks/
  - assets/icons/workouts/
  - assets/videos/workouts/Calisthenics/
  - assets/videos/workouts/Cardio/
  - assets/videos/workouts/Pilates/
  - assets/videos/workouts/Strengthtraining/
  - assets/videos/workouts/Yoga1/
  - assets/videos/workouts/Yoga2/
fonts:
- family: NotoSans
  fonts:
  - asset: assets/fonts/NotoSans/static/NotoSans-Regular.ttf
  - asset: assets/fonts/NotoSans/static/NotoSans-Bold.ttf
    weight: 700
