import 'package:diabetes/core/const/path_constants.dart';
import 'package:diabetes/core/const/text_constants.dart';
import 'package:diabetes/model/exercise_model.dart';
import 'package:diabetes/model/workout_model.dart';
import 'package:diabetes/screens/onboarding/widget/onboarding_title.dart';

class DataConstants {
  // Onboarding
  static final onboardingTiles = [
    const OnboardingTitle(
      title: TextConstants.onboarding1Title,
      mainText: TextConstants.onboarding1Description,
      imagePath: PathConstants.onboarding1,
    ),
    const OnboardingTitle(
      title: TextConstants.onboarding2Title,
      mainText: TextConstants.onboarding2Description,
      imagePath: PathConstants.onboarding2,
    ),
    const OnboardingTitle(
      title: TextConstants.onboarding3Title,
      mainText: TextConstants.onboarding3Description,
      imagePath: PathConstants.onboarding3,
    ),
  ];

  // Workouts
  static final List<WorkoutModel> workouts = [

    WorkoutModel(
        id: 'yoga1',
        title: TextConstants.yogaTitle1,
        exercises: TextConstants.yogaExercises1,
        minutes: TextConstants.yogaMinutes1,
        currentProgress: 0,
        progress: 5,
        image: PathConstants.yoga1,
        exerciseDataList: [
          ExerciseModel(
            id: 'downdogwalk',
            title: TextConstants.downDogWalk,
            minutes: TextConstants.downDogWalkMinutes,
            seconds: TextConstants.downDogWalkSeconds,
            progress: 0,
            video: PathConstants.downDogWalk,
            description: TextConstants.downDogWalkDescription,
            steps: [
              TextConstants.downDogWalkStep1,
              TextConstants.downDogWalkStep2,
              TextConstants.downDogWalkStep3,
              TextConstants.downDogWalkStep4,
            ],
          ),
          ExerciseModel(
            id: 'downdogwave',
            title: TextConstants.downDogWave,
            minutes: TextConstants.downDogWaveMinutes,
            seconds: TextConstants.downDogWalkSeconds,
            progress: 0,
            video: PathConstants.downDogWave,
            description: TextConstants.downDogWaveDescription,
            steps: [
              TextConstants.downDogWaveStep1,
              TextConstants.downDogWaveStep2,
              TextConstants.downDogWaveStep3,
              TextConstants.downDogWaveStep4,
            ],
          ),
          ExerciseModel(
            id: 'lungeHoldleftleg',
            title: TextConstants.lungeHoldLeftLeg,
            minutes: TextConstants.lungeHoldLeftLegMinutes,
            seconds: TextConstants.lungeHoldLeftLegSeconds,
            progress: 0,
            video: PathConstants.lungeHoldLeftLeg,
            description: TextConstants.lungeHoldLeftLegDescription,
            steps: [
              TextConstants.lungeHoldLeftLegStep1,
              TextConstants.lungeHoldLeftLegStep2,
              TextConstants.lungeHoldLeftLegStep3,
              TextConstants.lungeHoldLeftLegStep4,
              TextConstants.lungeHoldLeftLegStep5,
              TextConstants.lungeHoldLeftLegStep6,
              TextConstants.lungeHoldLeftLegStep7,
            ],
          ),
          ExerciseModel(
            id: 'siderotation',
            title: TextConstants.sideRotation,
            minutes: TextConstants.sideRotationMinutes,
            seconds: TextConstants.sideRotationSeconds,
            progress: 0,
            video: PathConstants.sideRotation,
            description: TextConstants.sideRotationDescription,
            steps: [
              TextConstants.sideRotationStep1,
              TextConstants.sideRotationStep2,
              TextConstants.sideRotationStep3,
              TextConstants.sideRotationStep4,
            ],
          ),
          ExerciseModel(
            id: 'warriorstretchrightside',
            title: TextConstants.warriorStretchRightSide1,
            minutes: TextConstants.warriorStretchRightSideMinutes1,
            seconds: TextConstants.warriorStretchRightSideSeconds1,
            progress: 0,
            video: PathConstants.warriorStretchRightSide1,
            description: TextConstants.warriorStretchRightSideDescription1,
            steps: [
              TextConstants.warriorStretchRightSide1Step1,
              TextConstants.warriorStretchRightSide1Step2,
              TextConstants.warriorStretchRightSide1Step3,
              TextConstants.warriorStretchRightSide1Step4,
            ],
          ),
        ]),
        
    WorkoutModel(
        id: 'yoga2',
        title: TextConstants.yogaTitle2,
        exercises: TextConstants.yogaExercises2,
        minutes: TextConstants.yogaMinutes2,
        currentProgress: 0,
        progress: 5,
        image: PathConstants.yoga2,
        exerciseDataList: [
          ExerciseModel(
            id: 'boatpose',
            title: TextConstants.boatPose,
            minutes: TextConstants.boatPoseMinutes,
            seconds: TextConstants.boatPoseSeconds,
            progress: 0,
            video: PathConstants.boatPose,
            description: TextConstants.boatPoseDescription,
            steps: [
              TextConstants.boatPoseStep1,
              TextConstants.boatPoseStep2,
              TextConstants.boatPoseStep3,
              TextConstants.boatPoseStep4,
              TextConstants.boatPoseStep5,
            ],
          ),
          ExerciseModel(
            id: 'onelegstandleftleg',
            title: TextConstants.oneLegStandLeftLeg,
            minutes: TextConstants.oneLegStandLeftLegMinutes,
            seconds: TextConstants.oneLegStandLeftLegSeconds,
            progress: 0,
            video: PathConstants.oneLegStandLeftLeg,
            description: TextConstants.oneLegStandLeftLegDescription,
            steps: [
              TextConstants.oneLegStandLeftLegStep1,
              TextConstants.oneLegStandLeftLegStep2,
              TextConstants.oneLegStandLeftLegStep3,
              TextConstants.oneLegStandLeftLegStep4,
              TextConstants.oneLegStandLeftLegStep5,
              TextConstants.oneLegStandLeftLegStep6,
              TextConstants.oneLegStandLeftLegStep7,
            ],
          ),
          ExerciseModel(
            id: 'onelegstandrightleg',
            title: TextConstants.oneLegStandRightLeg,
            minutes: TextConstants.oneLegStandRightLegMinutes,
            seconds: TextConstants.oneLegStandRightLegSeconds,
            progress: 0,
            video: PathConstants.oneLegStandRightLeg,
            description: TextConstants.oneLegStandRightLegDescription,
            steps: [
              TextConstants.oneLegStandRightLegStep1,
              TextConstants.oneLegStandRightLegStep2,
              TextConstants.oneLegStandRightLegStep3,
              TextConstants.oneLegStandRightLegStep4,
              TextConstants.oneLegStandRightLegStep5,
              TextConstants.oneLegStandRightLegStep6,
              TextConstants.oneLegStandRightLegStep7,
            ],
          ),
          ExerciseModel(
            id: 'warriorstretchleftside',
            title: TextConstants.warriorStretchLeftSide,
            minutes: TextConstants.warriorStretchLeftSideMinutes,
            seconds: TextConstants.warriorStretchLeftSideSeconds,
            progress: 0,
            video: PathConstants.warriorStretchLeftSide,
            description: TextConstants.warriorStretchLeftSideDescription,
            steps: [
              TextConstants.warriorStretchLeftSideStep1,
              TextConstants.warriorStretchLeftSideStep2,
              TextConstants.warriorStretchLeftSideStep3,
              TextConstants.warriorStretchLeftSideStep4,
            ],
          ),
          ExerciseModel(
            id: 'warriorstretchrightside2',
            title: TextConstants.warriorStretchRightSide2,
            minutes: TextConstants.warriorStretchRightSideMinutes2,
            seconds: TextConstants.warriorStretchRightSideSeconds2,
            progress: 0,
            video: PathConstants.warriorStretchRightSide2,
            description: TextConstants.warriorStretchRightSide2Description,
            steps: [
              TextConstants.warriorStretchRightSide2Step1,
              TextConstants.warriorStretchRightSide2Step2,
              TextConstants.warriorStretchRightSide2Step3,
              TextConstants.warriorStretchRightSide2Step4,
            ],
          ),
        ]),
    WorkoutModel(
        id: 'strengthtraining',
        title: TextConstants.strengthTrainingTitle,
        exercises: TextConstants.strengthTrainingExercises,
        minutes: TextConstants.strengthTrainingMinutes,
        currentProgress: 0,
        progress: 4,
        image: PathConstants.strengthtraining,
        exerciseDataList: [
          ExerciseModel(
            id: 'deadlifts',
            title: TextConstants.deadLifts,
            minutes: TextConstants.deadLiftsMinutes,
            seconds: TextConstants.deadLiftsSeconds,
            progress: 0,
            video: PathConstants.deadLifts,
            description: TextConstants.deadLiftsDescription,
            steps: [
              TextConstants.deadLiftsStep1,
              TextConstants.deadLiftsStep2,
              TextConstants.deadLiftsStep3,
              TextConstants.deadLiftsStep4,
            ],
          ),
          ExerciseModel(
            id: 'pullups',
            title: TextConstants.pullUps,
            minutes: TextConstants.pullUpsMinutes,
            seconds: TextConstants.pullUpsSeconds,
            progress: 0,
            video: PathConstants.pullUps,
            description: TextConstants.pullUpsDescription,
            steps: [
              TextConstants.pullUpsStep1,
              TextConstants.pullUpsStep2,
              TextConstants.pullUpsStep3,
            ],
          ),
          ExerciseModel(
            id: 'pushups',
            title: TextConstants.pushUps1,
            minutes: TextConstants.pushUps1Minutes,
            seconds: TextConstants.pushUps1Seconds,
            progress: 0,
            video: PathConstants.pushUps1,
            description: TextConstants.pushUps1Description,
            steps: [
              TextConstants.pushUps1Step1,
              TextConstants.pushUps1Step2,
              TextConstants.pushUps1Step3,
            ],
          ),
          ExerciseModel(
            id: 'squats',
            title: TextConstants.squats,
            minutes: TextConstants.squatsMinutes,
            seconds: TextConstants.squatsSeconds,
            progress: 0,
            video: PathConstants.squats,
            description: TextConstants.squatsDescription,
            steps: [
              TextConstants.squatsStep1,
              TextConstants.squatsStep2,
              TextConstants.squatsStep3,
              TextConstants.squatsStep4,
              TextConstants.squatsStep5,
            ],
          ),
        ]),
    WorkoutModel(
        id: 'pilates',
        title: TextConstants.pilatesTitle,
        exercises: TextConstants.pilatesExercises,
        minutes: TextConstants.pilatesMinutes,
        currentProgress: 0,
        progress: 5,
        image: PathConstants.pilates,
        exerciseDataList: [
          ExerciseModel(
            id: 'crisscross',
            title: TextConstants.crissCross,
            minutes: TextConstants.crissCrossMinutes,
            seconds: TextConstants.crissCrossSeconds,
            progress: 0,
            video: PathConstants.crissCross,
            description: TextConstants.crissCrossDescription,
            steps: [
              TextConstants.crissCrossStep1,
              TextConstants.crissCrossStep2,
              TextConstants.crissCrossStep3,
              TextConstants.crissCrossStep4,
            ],
          ),
          ExerciseModel(
            id: 'doublelegstretch',
            title: TextConstants.doubleLegStretch,
            minutes: TextConstants.doubleLegStretchMinutes,
            seconds: TextConstants.doubleLegStretchSeconds,
            progress: 0,
            video: PathConstants.doubleLegStretch,
            description: TextConstants.doubleLegStretchDescription,
            steps: [
              TextConstants.doubleLegStretchStep1,
              TextConstants.doubleLegStretchStep2,
              TextConstants.doubleLegStretchStep3,
            ],
          ),
          ExerciseModel(
            id: 'pilatesonehundred',
            title: TextConstants.pilatesOneHundred,
            minutes: TextConstants.pilatesOneHundredMinutes,
            seconds: TextConstants.pilatesOneHundredSeconds,
            progress: 0,
            video: PathConstants.pilatesOneHundred,
            description: TextConstants.pilatesOneHundredDescription,
            steps: [
              TextConstants.pilatesOneHundredStep1,
              TextConstants.pilatesOneHundredStep2,
              TextConstants.pilatesOneHundredStep3,
              TextConstants.pilatesOneHundredStep4,
              TextConstants.pilatesOneHundredStep5,
            ],
          ),
          ExerciseModel(
            id: 'scissorkick',
            title: TextConstants.scissorKick,
            minutes: TextConstants.scissorKickMinutes,
            seconds: TextConstants.scissorKickSeconds,
            progress: 0,
            video: PathConstants.scissorKick,
            description: TextConstants.scissorKickDescription,
            steps: [
              TextConstants.scissorKickStep1,
              TextConstants.scissorKickStep2,
              TextConstants.scissorKickStep3,
              TextConstants.scissorKickStep4,
            ],
          ),
          ExerciseModel(
            id: 'singlelegstretch',
            title: TextConstants.singleLegStretch,
            minutes: TextConstants.singleLegStretchMinutes,
            seconds: TextConstants.singleLegStretchSeconds,
            progress: 0,
            video: PathConstants.singleLegStretch,
            description: TextConstants.singleLegStretchDescription,
            steps: [
              TextConstants.singleLegStretchStep1,
              TextConstants.singleLegStretchStep2,
              TextConstants.singleLegStretchStep3,
              TextConstants.singleLegStretchStep4,
            ],
          ),
        ]),
    WorkoutModel(
        id: 'cardio',
        title: TextConstants.cardioTitle,
        exercises: TextConstants.cardioExercises,
        minutes: TextConstants.cardioMinutes,
        currentProgress: 0,
        progress: 5,
        image: PathConstants.cardio,
        exerciseDataList: [
          ExerciseModel(
            id: 'ankletapback',
            title: TextConstants.ankleTapBack,
            minutes: TextConstants.ankleTapBackMinutes,
            seconds: TextConstants.ankleTapBackSeconds,
            progress: 0,
            video: PathConstants.ankleTapBack,
            description: TextConstants.ankleTapBackDescription,
            steps: [
              TextConstants.ankleTapBackStep1,
              TextConstants.ankleTapBackStep2,
              TextConstants.ankleTapBackStep3,
              TextConstants.ankleTapBackStep4,
            ],
          ),
          ExerciseModel(
            id: 'ankletapfront',
            title: TextConstants.ankleTapFront,
            minutes: TextConstants.ankleTapFrontMinutes,
            seconds: TextConstants.ankleTapFrontSeconds,
            progress: 0,
            video: PathConstants.ankleTapFront,
            description: TextConstants.ankleTapFrontDescription,
            steps: [
              TextConstants.ankleTapFrontStep1,
              TextConstants.ankleTapFrontStep2,
              TextConstants.ankleTapFrontStep3,
              TextConstants.ankleTapFrontStep4,
              TextConstants.ankleTapFrontStep5,
              TextConstants.ankleTapFrontStep6,
            ],
          ),
          ExerciseModel(
            id: 'armlifthighknee',
            title: TextConstants.armLiftHighKnee,
            minutes: TextConstants.armLiftHighKneeMinutes,
            seconds: TextConstants.armLiftHighKneeSeconds,
            progress: 0,
            video: PathConstants.armLiftHighKnee,
            description: TextConstants.armLiftHighKneeDescription,
            steps: [
              TextConstants.armLiftHighKneeStep1,
              TextConstants.armLiftHighKneeStep2,
              TextConstants.armLiftHighKneeStep3,
              TextConstants.armLiftHighKneeStep4,
              TextConstants.armLiftHighKneeStep5,
              TextConstants.armLiftHighKneeStep6,
            ],
          ),
          ExerciseModel(
            id: 'sidetoside',
            title: TextConstants.sideToSide,
            minutes: TextConstants.sideToSideMinutes,
            seconds: TextConstants.sideToSideSeconds,
            progress: 0,
            video: PathConstants.sideToSide,
            description: TextConstants.sideToSideDescription,
            steps: [
              TextConstants.sideToSideStep1,
              TextConstants.sideToSideStep2,
              TextConstants.sideToSideStep3,
              TextConstants.sideToSideStep4,
              TextConstants.sideToSideStep5,
            ],
          ),
          ExerciseModel(
            id: 'walking',
            title: TextConstants.walking,
            minutes: TextConstants.walkingMinutes,
            seconds: TextConstants.walkingSeconds,
            progress: 0,
            video: PathConstants.walking,
            description: TextConstants.walkingDescription,
            steps: [
              TextConstants.walkingStep1,
              TextConstants.walkingStep2,
            ],
          ),
        ]),
    WorkoutModel(
        id: 'calisthenics',
        title: TextConstants.calisthenicsTitle,
        exercises: TextConstants.calisthenicsExercises,
        minutes: TextConstants.calisthenicsMinutes,
        currentProgress: 0,
        progress: 4,
        image: PathConstants.calisthenics,
        exerciseDataList: [
          ExerciseModel(
            id: 'lunges',
            title: TextConstants.lunges,
            minutes: TextConstants.lungesMinutes,
            seconds: TextConstants.lungesSeconds,
            progress: 0,
            video: PathConstants.lunges,
            description: TextConstants.lungesDescription,
            steps: [
              TextConstants.lungesStep1,
              TextConstants.lungesStep2,
            ],
          ),
          ExerciseModel(
            id: 'plank',
            title: TextConstants.plank,
            minutes: TextConstants.plankMinutes,
            seconds: TextConstants.plankSeconds,
            progress: 0,
            video: PathConstants.plank,
            description: TextConstants.plankDescription,
            steps: [
              TextConstants.plankStep1,
              TextConstants.plankStep2,
              TextConstants.plankStep3,
              TextConstants.plankStep4,
            ],
          ),
          ExerciseModel(
            id: 'pushups',
            title: TextConstants.pushUps,
            minutes: TextConstants.pushUpsMinutes,
            seconds: TextConstants.pushUpsSeconds,
            progress: 0,
            video: PathConstants.pushUps,
            description: TextConstants.pushUpsDescription,
            steps: [
              TextConstants.pushUpsStep1,
              TextConstants.pushUpsStep2,
              TextConstants.pushUpsStep3,
              TextConstants.pushUpsStep4,
            ],
          ),
          ExerciseModel(
            id: 'tricedips',
            title: TextConstants.triceDips,
            minutes: TextConstants.triceDipsMinutes,
            seconds: TextConstants.triceDipsSeconds,
            progress: 0,
            video: PathConstants.triceDips,
            description: TextConstants.triceDipsDescription,
            steps: [
              TextConstants.triceDipsStep1,
              TextConstants.triceDipsStep2,
              TextConstants.triceDipsStep3,
              TextConstants.triceDipsStep4,
            ],
          ),
        ]),
  ];

  // Reminder
  static List<String> reminderDays = [
    TextConstants.everyday,
    TextConstants.monday_friday,
    TextConstants.weekends,
    TextConstants.monday,
    TextConstants.tuesday,
    TextConstants.wednesday,
    TextConstants.thursday,
    TextConstants.friday,
    TextConstants.saturday,
    TextConstants.sunday,
  ];
}
